create table SampleSB_SampleSB (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	samplesbId LONG not null primary key,
	title VARCHAR(80) null,
	samplesbBooleanStat BOOLEAN,
	samplesbDateTime DATE null,
	samplesbDocumentLibrary VARCHAR(512) null,
	samplesbDouble DOUBLE,
	samplesbInteger INTEGER,
	samplesbRichText TEXT null,
	samplesbText TEXT null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	urlTitle VARCHAR(75) null,
	samplesbTitleName VARCHAR(255) null,
	samplesbSummaryName TEXT null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);